### ISSUE TITLE
ecto.TypeMismatch when running `object_recognition_capture capture`

### ISSUE THREAD

**Issue by severin-lemaignan** [wg-perception/capture#21]
While trying to follow the [ORK tutorial](http://wg-perception.github.io/object_recognition_core/quickguide.html), I hit a crash:

```
$ rosrun object_recognition_capture capture --seg_z_min 0.01 -o my_mug.bag
Traceback (most recent call last):
  File "/opt/ros/jade/lib/object_recognition_capture/capture", line 72, in <module>
    fps=options.fps
  File "/opt/ros/jade/lib/python2.7/dist-packages/object_recognition_capture/openni_capture.py", line 207, in create_capture_plasm
    plasm.connect(graph)
ecto.TypeMismatch:            exception_type  TypeMismatch
[to_key] = image

[to_cell] = Bag Writer if R|T

[from_key] = image

[from_cell] = ecto_ros::Mat2Image

[to_typename] = boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > const>

[from_typename] = boost::shared_ptr<sensor_msgs::Image_<std::allocator<void> > >
```

At first sight, the types look compatible to me (*from* `non const` *to* `const` should not be an issue, right?)...

Note that the same capture in **preview** mode, works well. ie,
```
$ rosrun object_recognition_capture capture --seg_z_min 0.01 -o my_mug.bag --preview
```
works as expected.

Found on Ubuntu 15.10, fresh ROS, manually compiled.

**Comment by severin-lemaignan** [comment]
@vrabaud By making a checkout of [ecto-ros](https://github.com/plasmodic/ecto_ros) at commit 7c255f895167e9a8da1f9a60c055673ab8e28f61 and recompiling, the issue vanishes. I did not yet bisect the exact commit, but it seems we have a regression there...

**Comment by vrabaud** [comment]
Yes, https://github.com/plasmodic/ecto_ros/commit/886db93028eec9977ccf806d1f516cd94cd33a3e fixes it.
ecto_ros 0.4.8 or above has the fix. It is way out by now :) thx for reporting !
