### ISSUE TITLE
ecto.CellException while running object_recognition_capture upload

### ISSUE THREAD

**Issue by tomassykora** [wg-perception/capture#22]
I'm following these tutorials: http://wg-perception.github.io/object_recognition_core/quickguide.html#quickguide
But when I run object_recognition_capture upload, I get this output:
Stored new object with id: 51679ad398cd1701a5182dae7a000549
Loading bag with : final.bag
running graph
Opening bag: final.bag
Inserting frame: 0
libpng warning: Image width is zero in IHDR
libpng warning: Image height is zero in IHDR
libpng error: Invalid IHDR data
OpenCV Error: Assertion failed (code) in imencode, file /build/buildd/opencv-2.4.8+dfsg1/modules/highgui/src/loadsave.cpp, line 430
Traceback (most recent call last):
  File "/home/tomas/libs_and_graphics/ws/src/ork_capture/apps/upload", line 145, in <module>
    session = compute_for_bag_with_mask_pose(bag, obj, args)
  File "/home/tomas/libs_and_graphics/ws/src/ork_capture/apps/upload", line 105, in compute_for_bag_with_mask_pose
    run_plasm(args, plasm, locals=vars())
  File "/home/tomas/libs_and_graphics/ws/src/ecto/python/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = db_inserter

[cell_type] = object_recognition_core::prototypes::ObservationInserter

[function_name] = process_with_only_these_inputs

[type] = cv::Exception

[what] = /build/buildd/opencv-2.4.8+dfsg1/modules/highgui/src/loadsave.cpp:430: error: (-215) code in function imencode

**Comment by JimmyDaSilva** [comment]
Hi @nlyubova, @vrabaud .

I have exactly the same problem as @tomassykora here. 
The capture node displays correctly both rgb and mask images, but the images saved in the .bag seems to contain an empty header.
Then, when trying to upload the files to the database, imencode fails because "encoding" in the image header is "[ ]"

Thank you for your time and help :)

**Comment by JimmyDaSilva** [comment]
Here is proof that it's really `sensor_msgs/Image.encoding` that isn't set.

In the following image I replay the bag file I created witht the capture pipeline.
The image is there and not fully filled of zero so contains all the information, except the encoding.
![bag_encoding_empty](https://cloud.githubusercontent.com/assets/5452370/13253320/d1dff7cc-da3b-11e5-9bfb-690ceedbe972.png)

**Comment by JimmyDaSilva** [comment]
@tomassykora I got it working again. Capture, upload, and reconstruction worked fine :)
You just need to add the encoding of the images in 3 lines:

https://github.com/wg-perception/capture/blob/master/python/object_recognition_capture/openni_capture.py#L145
`rgbMsg = Mat2Image(frame_id='/camera_rgb_optical_frame', swap_rgb=False, encoding='bgr8')`

https://github.com/wg-perception/capture/blob/master/python/object_recognition_capture/openni_capture.py#L146
`depthMsg = Mat2Image(frame_id='/camera_rgb_optical_frame', encoding='16UC1')`

https://github.com/wg-perception/capture/blob/master/python/object_recognition_capture/openni_capture.py#L157
`maskMsg = Mat2Image(frame_id='/camera_rgb_optical_frame', encoding='8UC1')`


@vrabaud This could be problematic if encoding depends on openni, openni2, kinect2_bridge,...
How could get access initial encoding in that code? Should the change be made somewhere else ?

Do you confirm that 'bgr8', '16UC1' and '8UC1' are the right encodings to use here ?

Thanks!

**Comment by vrabaud** [comment]
Hi @JimmyDaSilva , thx for the fixes. I confirm what you have is good. Can you please make a pull request ? Thx.

**Comment by JimmyDaSilva** [comment]
@vrabaud This can be closed. Thank you for the merge and release :)

**Comment by vrabaud** [comment]
cool, thx !
