### ISSUE TITLE
[problem] Error while capturing new Object

### ISSUE THREAD

**Issue by xMutzelx** [wg-perception/capture#27]
Hello,
I am following this tutorial: http://wg-perception.github.io/capture/index.html#ork-capture
When I try to run this command: 
`rosrun object_recognition_capture capture --seg_z_min 0.01 -o pringles.bag --preview`

I get the following error:
`Registration? 1
Sync? 0
python: /usr/include/boost/smart_ptr/shared_ptr.hpp:646: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = xn::NodeInfo; typename boost::detail::sp_dereference<T>::type = xn::NodeInfo&]: Assertion`px != 0' failed.
Aborted (core dumped)
`
Do you have any suggestions? Thank you for your help.

I am using Ubuntu 14.04, Ros Indigo, OpenCV 2.4.11 and Python 2.7.6

**Comment by xMutzelx** [comment]
Wow, I tried to fix this problem the last 3 hours. After I posted my issue here, I found my error ...
My problem was, that I ran `rosrun topic_tools relay /camera/depth_registered/image_raw /camera/depth_registered/image` earlier. 
After I shut this process down, everything works fine. Thank you anyway.

**Comment by xMutzelx** [comment]
After a restart I get the same error again :( and I can't fix it.

**Comment by hexroytom** [comment]
Hi, xMutzelx.
I ran into the same errors with you. Do u have any solutions right now?
I am using Ubuntu 14.04, Ros Indigo, OpenCV 3.1 ,Python 2.7.6, and Kinect V1

**Comment by xMutzelx** [comment]
I found my mistake. As it seems, the source_node tries to access the camera, even if openni_launch is already running. Just do not run `roslaunch openni_launch openni.launch` or `roslaunch openni2_launch openni2.launch` and it should work. I hope I could help you @hexroytom .

**Comment by hexroytom** [comment]
Thank you. It solves my problem now. @xMutzelx

**Comment by saspelund** [comment]
How did it take me this long to find this thread?! I have been searching too long for the answer to this problem that has been plaguing me for much too long!

Thank you!

The tutorial should be edited to reflect this. It explicitly tells you to launch openni. Who should we contact?

Annnnnnd now it's failing again.... I can run
`rosrun object_recognition_capture orb_templat -o my_textured_plane`
but not
`rosrun object_recognition_capture orb_rack --track_directory my_textured_plane`
which gives me the

```
Registration? 1
Sync? 0
python: /usr/include/boost/smart_ptr/shared_ptr.hpp:646: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = xn::NodeInfo; typename boost::detail::sp_dereference<T>::type = xn::NodeInfo&]: Assertion `px != 0' failed.
Aborted (core dumped)
```

error again. But then after 20 tries it works again......

**Comment by xMutzelx** [comment]
@saspelund I am happy I could help you. Sadly I am using [this](https://github.com/wg-perception/capture/tree/master/apps/capture_board) and not the orb-template function. I can't help you with your error sorry, but I can give you an alternative. It works like a charm. If you can print it out, I really recommend it. 
Commands:

```
/* A preview mode to prepare everything */
rosrun object_recognition_capture capture --seg_z_min 0.01 -o OBJECT_NAME.bag --preview

/* Capture some pictures */
rosrun object_recognition_capture capture -n NUMBER_OF_FRAMES --seg_z_min 0.01 -o OBJECT_NAME.bag

/* Upload them to your database */
rosrun object_recognition_capture upload -i OBJECT_NAME.bag -n 'object_name' testTAG musicTAG blaTAG --commit

/* Reconstruction of all objects */
rosrun object_recognition_reconstruction mesh_object --all --visualize --commit

/* Reconstruction of one specific  object */
rosrun object_recognition_reconstruction mesh_object -s SESSION_ID --visualize --commit
```

**Comment by saspelund** [comment]
So I am also using the capture board but the instructions were not clear and so I was running the orb-template functions. Now I am omitting that part of the code and it works decently well. Thanks for your help.

However, I am unable to mesh my objects as per [this issue](https://github.com/wg-perception/reconstruction/issues/7#issuecomment-226614894). I have been tinkering around with trying to figure out why it can't find my bag files but without success. Seems I can't take more than two steps without hitting a wall :P
